### ISSUE TITLE
The csync module owncloud could not be loaded

### ISSUE THREAD

**Issue by yavama** [csawyerYumaed/pyOwnCloud#78] opened 2016-02-22 08:58 UTC
i have this message when runing oclient 
what's the problem ?

root-DEBUG: ProgressBar not available
csync.csynclib.pre-DEBUG: Found ocsync at /usr/lib/libocsync.so.0
root-DEBUG: getConfigPath: /home/dhouha/.local/share/data/ownCloud
Traceback (most recent call last):
  File "/usr/local/bin/oclient", line 9, in <module>
    load_entry_point('pyOwnCloud==0.4.pre', 'console_scripts', 'oclient')()
  File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csync.py", line 495, in main
    startSync(parser)
  File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csync.py", line 408, in startSync
    cfg = getConfig(parser)
  File "/usr/local/lib/python2.7/dist-packages/pyOwnCloud-0.4.pre-py2.7.egg/csync/csync.py", line 379, in getConfig
    cfg = dict(c.items('ownCloud'))
  File "/usr/lib/python2.7/ConfigParser.py", line 642, in items
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'ownCloud'

**Comment by yavama** [comment] 2016-02-23 09:21
i've solved it with adding a new section in owncloud.cfg but now i got this :/
root-DEBUG: ProgressBar not available
csync.csynclib.pre-DEBUG: Found ocsync at /usr/lib/libocsync.so.0
root-DEBUG: getConfigPath: /home/dhouha/.local/share/data/ownCloud
pyOC-INFO: Syncing /var/www/owncloud/ to owncloud://127.0.0.1/owncloud/remote.php/webdav/clientsync, logging in as user: dhouhama
ocsync-CRITICAL: csync_init: The csync module owncloud could not be loaded.
pyOC-ERROR: csync_init exited with -1, csync(0.90.4) error 5: None

**Comment by csawyerYumaed** [comment] 2016-02-23 14:39
duplicate of #75

**Closed by csawyerYumaed** 2016-02-23 14:39 UTC

**Comment by yavama** [comment] 2016-02-24 10:31
@csawyerYumaed 
it says "Found ocsync at /usr/lib/libocsync.so.0" 
i 'think it's not a problem of library !
